#Total revenue generated by male vs female

SELECT SUM(purchase_amount), gender
FROM customer
Group by gender;

#wich customer used a discount but still spent more than the average purchase amount

SELECT customer_id, purchase_amount
from customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount)
                                                      FROM customer);

#Wich are the top 5 products with the highest average review rating

SELECT item_purchased, AVG(review_rating) as 'average_review_rating'
FROM customer
GROUP BY category
ORDER BY AVG(review_rating) DESC
LIMIT 5;

# Compare the average purchase amounts between standard and express shipping
 SELECT ROUND(AVG(purchase_amount),2) as 'average purchase amount', shipping_type
from customer
where shipping_type in ('Express','Standard')
GROUP BY shipping_type;

#Do subscribed customers spend more?
SELECT subscription_status,
COUNT(customer_id)as'total customers',
ROUND(SUM(purchase_amount),2) as 'total revenue',
ROUND(AVG(purchase_amount),2) as 'avg purcchase amount'
FROM customer
group by subscription_status;

# Wich 5 products have the highest percentage of purchases with discounts applied
SELECT item_purchased, 
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 else 0 end)/COUNT(*))*100,2) as discount_rate
from customer 
group by item_purchased
order by discount_rate DESC
LIMIt 5;

#Segment customers into new, returning, loyal based on their total number of  purchases, and show the count of each segment
SELECT customer_segment, COUNT(*) AS Number_of_customers
FROM (
    SELECT customer_id, previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS customer_type
GROUP BY customer_segment;

#What are the top 3 most purchased products within each category

SELECT t1.category,
       t1.item_purchased,
       t1.total_orders
FROM (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
) AS t1
WHERE (
    SELECT COUNT(*)
    FROM (
        SELECT category,
               item_purchased,
               COUNT(customer_id) AS total_orders
        FROM customer
        GROUP BY category, item_purchased
    ) AS t2
    WHERE t2.category = t1.category
      AND t2.total_orders > t1.total_orders
) < 3
ORDER BY t1.category, t1.total_orders DESC;

# are customers who are repeat buyers ( more than 5 previous purchases ) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

#What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC;